CREATE TABLE IF NOT EXISTS [Entity] (
  [Id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  [Name] NVARCHAR(256), 
  [Type] INT NOT NULL DEFAULT 1, 
  [Extension] NVARCHAR(256) NOT NULL,
  [ParentId] INT CONSTRAINT [FK_ENTITY_PARENT] REFERENCES [Entity]([Id]) ON DELETE SET NULL ON UPDATE CASCADE);$


CREATE TABLE IF NOT EXISTS [EntityTag] (
  [EntityId] INTEGER NOT NULL, 
  [TagId] INTEGER NOT NULL, 
  CONSTRAINT [] PRIMARY KEY ([EntityId], [TagId]));$


CREATE TABLE IF NOT EXISTS [Tag] (
  [Id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
  [Name] NVARCHAR(256) CONSTRAINT [UQS_TAG_NAME] UNIQUE);

