using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Altus.Core;
using System.ComponentModel;
using Altus.Core.Data;

namespace Altus.Core.Component
{
    [StorageMapping("Component")]
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true, Inherited = true)]
    public class ComponentAttribute : Attribute
    {
        private string _name;
        private string _description;
        private string _type;
        private Type _ctype;
        private string[] _dependencies = new string[0];
        private object[] _ctorArgs = new object[0];

        public ComponentAttribute() { Enabled = true; Reflect = true; }

        [StorageFieldMapping("Id", StorageFieldModifiers.Key | StorageFieldModifiers.AutoGenerated)]
        public int Id { get; set; }

        [StorageFieldMapping("Name")]
        public string Name
        {
            get
            {
                if (string.IsNullOrEmpty(_name))
                {
                    return _type;
                }
                else
                {
                    return _name;
                }
            }
            set { _name = value; }
        }

        [StorageFieldMapping("Description")]
        public string Description
        {
            get { return _description; }
            set { _description = value; }
        }

        [StorageFieldMapping("CLRType")]
        public string Component
        {
            get { return _type; }
            set 
            {
                
                _type = value;
            }
        }

        public bool IsValid { get; private set; }
        public bool IsValidated { get; private set; }

        public Type ComponentType
        {
            get 
            {
                if (!IsValidated)
                {
                    try
                    {
                        _ctype = TypeHelper.GetType(_type);
                        _type = _ctype.AssemblyQualifiedName;
                        IsValid = true;
                    }
                    catch
                    {
                        IsValid = false;
                    }
                    finally
                    {
                        IsValidated = true;
                    }
                }
                return _ctype; 
            }
            set 
            { 
                _ctype = value;
                if (value == null)
                {
                    _type = null;
                    IsValidated = false;
                    IsValid = false;
                }
                else
                {
                    _type = value.AssemblyQualifiedName;
                    IsValidated = true;
                    IsValid = true;
                }
            }
        }
        /// <summary>
        /// Gets/sets the list of Component Names that should be loaded prior to
        /// loading this component
        /// </summary>
        
        public string[] Dependencies
        {
            get
            {
                return _dependencies;
            }
            set
            {
                _dependencies = value;
            }
        }

        public object[] CtorArgs
        {
            get { return _ctorArgs; }
            set { _ctorArgs = value; }
        }

        [StorageFieldMapping("Dependencies")]
        private string DependenciesString
        {
            get
            {
                StringBuilder sb = new StringBuilder();
                foreach (string s in this.Dependencies)
                {
                    if (sb.Length > 0)
                        sb.Append(", ");
                    sb.Append(s);
                }
                return sb.ToString();
            }
            set
            {
                if (value != null)
                    this.Dependencies = value.Split(',');
            }
        }
        [StorageFieldMapping("Enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// Allows for components to be sorted relative to each other.  Bigger numbers are executed before littler numbers.
        /// </summary>
        public ushort Priority { get; set; }

        public IComponent Instance { get; set; }

        public bool Reflect { get; set; }

        public override string ToString()
        {
            if (Name.Equals(Component)) return Name;
            return string.Format("{0} [{1}]",
                Name,
                Component);
        }
    }
}

