//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Altus.GEM.Schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="modelex", IsNullable=false)]
    public partial class ModelEx {
        
        private ModelExConfiguration configurationField;
        
        private Entity[] entityModelsField;
        
        private CalculationModel[] calculationModelsField;
        
        private ReportModel[] reportModelsField;
        
        private string nameField;
        
        /// <remarks/>
        public ModelExConfiguration Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("EntityModel", IsNullable=false)]
        public Entity[] EntityModels {
            get {
                return this.entityModelsField;
            }
            set {
                this.entityModelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CalculationModel[] CalculationModels {
            get {
                return this.calculationModelsField;
            }
            set {
                this.calculationModelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ReportModel[] ReportModels {
            get {
                return this.reportModelsField;
            }
            set {
                this.reportModelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class ModelExConfiguration {
        
        private DataSource dataSourceField;
        
        private ModelExConfigurationLocal localField;
        
        /// <remarks/>
        public DataSource DataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
            }
        }
        
        /// <remarks/>
        public ModelExConfigurationLocal Local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodeEntityDataSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AssemblyEntityDataSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DBEntityDataSource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DBDataSource))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class DataSource {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExcelReportModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class ReportModel {
        
        private ReportModelCalculationModel[] calculationModelsField;
        
        private ReportModelEntity[] entitiesField;
        
        private ParameterMapping[] parameterMappingsField;
        
        private View[] configurationViewsField;
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CalculationModel", IsNullable=false)]
        public ReportModelCalculationModel[] CalculationModels {
            get {
                return this.calculationModelsField;
            }
            set {
                this.calculationModelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Entity", IsNullable=false)]
        public ReportModelEntity[] Entities {
            get {
                return this.entitiesField;
            }
            set {
                this.entitiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ParameterMapping[] ParameterMappings {
            get {
                return this.parameterMappingsField;
            }
            set {
                this.parameterMappingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ConfigurationView", IsNullable=false)]
        public View[] ConfigurationViews {
            get {
                return this.configurationViewsField;
            }
            set {
                this.configurationViewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class ReportModelCalculationModel {
        
        private string modelIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string modelId {
            get {
                return this.modelIdField;
            }
            set {
                this.modelIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class ReportModelEntity {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class ParameterMapping {
        
        private string entityIdField;
        
        private string modelIdField;
        
        private string parameterField;
        
        private string entityPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string entityId {
            get {
                return this.entityIdField;
            }
            set {
                this.entityIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string modelId {
            get {
                return this.modelIdField;
            }
            set {
                this.modelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entityProperty {
            get {
                return this.entityPropertyField;
            }
            set {
                this.entityPropertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WinformView))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WpfView))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StandardView))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class View {
        
        private string typeField;
        
        private string windowNameField;
        
        public View() {
            this.windowNameField = "Main";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Main")]
        public string windowName {
            get {
                return this.windowNameField;
            }
            set {
                this.windowNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class WinformView : View {
        
        private WinformViewReference[] referencesField;
        
        private string codeBaseField;
        
        private string typeNameField;
        
        private string initMethodField;
        
        public WinformView() {
            this.initMethodField = "Initialize";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable=false)]
        public WinformViewReference[] References {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeBase {
            get {
                return this.codeBaseField;
            }
            set {
                this.codeBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Initialize")]
        public string initMethod {
            get {
                return this.initMethodField;
            }
            set {
                this.initMethodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class WinformViewReference {
        
        private string codeBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeBase {
            get {
                return this.codeBaseField;
            }
            set {
                this.codeBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class WpfView : View {
        
        private string viewXAMLField;
        
        private string codeField;
        
        private WpfViewReference[] referencesField;
        
        private string styleXAMLField;
        
        private Resource[] resourcesField;
        
        private WpfViewWpfViewType wpfViewTypeField;
        
        /// <remarks/>
        public string ViewXAML {
            get {
                return this.viewXAMLField;
            }
            set {
                this.viewXAMLField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Reference", IsNullable=false)]
        public WpfViewReference[] References {
            get {
                return this.referencesField;
            }
            set {
                this.referencesField = value;
            }
        }
        
        /// <remarks/>
        public string StyleXAML {
            get {
                return this.styleXAMLField;
            }
            set {
                this.styleXAMLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Resource[] Resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public WpfViewWpfViewType wpfViewType {
            get {
                return this.wpfViewTypeField;
            }
            set {
                this.wpfViewTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class WpfViewReference {
        
        private string codeBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeBase {
            get {
                return this.codeBaseField;
            }
            set {
                this.codeBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BinaryResource))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileResource))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class Resource {
        
        private string destinationPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string destinationPath {
            get {
                return this.destinationPathField;
            }
            set {
                this.destinationPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class BinaryResource : Resource {
        
        private byte[] dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class FileResource : Resource {
        
        private string sourcePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sourcePath {
            get {
                return this.sourcePathField;
            }
            set {
                this.sourcePathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public enum WpfViewWpfViewType {
        
        /// <remarks/>
        DataTemplate,
        
        /// <remarks/>
        UserControl,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class StandardView : View {
        
        private StandardViewColumn[] columnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Column", IsNullable=false)]
        public StandardViewColumn[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScalarValueViewColumn))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityMappedViewColumn))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class StandardViewColumn {
        
        private string nameField;
        
        private string displayFormatField;
        
        private string transformFunctionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string displayFormat {
            get {
                return this.displayFormatField;
            }
            set {
                this.displayFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transformFunction {
            get {
                return this.transformFunctionField;
            }
            set {
                this.transformFunctionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class ScalarValueViewColumn : StandardViewColumn {
        
        private string scalarValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scalarValue {
            get {
                return this.scalarValueField;
            }
            set {
                this.scalarValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class EntityMappedViewColumn : StandardViewColumn {
        
        private string entityPropertyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entityProperty {
            get {
                return this.entityPropertyField;
            }
            set {
                this.entityPropertyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class ExcelReportModel : ReportModel {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodeCalculationModel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkflowCalculationModel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class CalculationModel {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class CodeCalculationModel : CalculationModel {
        
        private object codeField;
        
        /// <remarks/>
        public object Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class WorkflowCalculationModel : CalculationModel {
        
        private string xamlField;
        
        /// <remarks/>
        public string Xaml {
            get {
                return this.xamlField;
            }
            set {
                this.xamlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CodeBehavior))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DefaultBehavior))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class Behavior {
        
        private BehaviorAction actionField;
        
        private int priorityField;
        
        private bool priorityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public BehaviorAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public enum BehaviorAction {
        
        /// <remarks/>
        OnOpen,
        
        /// <remarks/>
        OnCreate,
        
        /// <remarks/>
        OnRead,
        
        /// <remarks/>
        OnUpdate,
        
        /// <remarks/>
        OnDelete,
        
        /// <remarks/>
        OnClose,
        
        /// <remarks/>
        OnSelect,
        
        /// <remarks/>
        OnDeselect,
        
        /// <remarks/>
        OnDragStart,
        
        /// <remarks/>
        OnDragComplete,
        
        /// <remarks/>
        OnPrint,
        
        /// <remarks/>
        OnPropertiesShow,
        
        /// <remarks/>
        OnPropertiesHide,
        
        /// <remarks/>
        OnRename,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class CodeBehavior : Behavior {
        
        private object codeField;
        
        private string inputParameterNameField;
        
        public CodeBehavior() {
            this.inputParameterNameField = "e";
        }
        
        /// <remarks/>
        public object Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("e")]
        public string inputParameterName {
            get {
                return this.inputParameterNameField;
            }
            set {
                this.inputParameterNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class DefaultBehavior : Behavior {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReportFileEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationFileEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataFileEntity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class Entity {
        
        private Property[] propertiesField;
        
        private DataSource dataSourceField;
        
        private string codeField;
        
        private Behavior[] behaviorsField;
        
        private string[] tagsField;
        
        private View[] customViewsField;
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Property[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        public DataSource DataSource {
            get {
                return this.dataSourceField;
            }
            set {
                this.dataSourceField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Behavior[] Behaviors {
            get {
                return this.behaviorsField;
            }
            set {
                this.behaviorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tag", IsNullable=false)]
        public string[] Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CustomView", IsNullable=false)]
        public View[] CustomViews {
            get {
                return this.customViewsField;
            }
            set {
                this.customViewsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EvaluatedProperty))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataPropertyArray))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataPropertyScalar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ScalarProperty))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class Property {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class EvaluatedProperty : Property {
        
        private CS_Types typeField;
        
        private string expressionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CS_Types type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string expression {
            get {
                return this.expressionField;
            }
            set {
                this.expressionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public enum CS_Types {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.String")]
        SystemString,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Int32")]
        SystemInt32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Int64")]
        SystemInt64,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Single")]
        SystemSingle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Double")]
        SystemDouble,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.DateTime")]
        SystemDateTime,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Boolean")]
        SystemBoolean,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Byte")]
        SystemByte,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.SByte")]
        SystemSByte,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Char")]
        SystemChar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.UInt16")]
        SystemUInt16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.UInt32")]
        SystemUInt32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.UInt64")]
        SystemUInt64,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Int16")]
        SystemInt16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Decimal")]
        SystemDecimal,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Byte[]")]
        SystemByte1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class DataPropertyArray : Property {
        
        private CS_ArrayTypes typeField;
        
        private string sourceField;
        
        private int recordsetIndexField;
        
        public DataPropertyArray() {
            this.recordsetIndexField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CS_ArrayTypes type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int recordsetIndex {
            get {
                return this.recordsetIndexField;
            }
            set {
                this.recordsetIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public enum CS_ArrayTypes {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.String[]")]
        SystemString,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Int32[]")]
        SystemInt32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Int64[]")]
        SystemInt64,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Single[]")]
        SystemSingle,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Double[]")]
        SystemDouble,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.DateTime[]")]
        SystemDateTime,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Boolean[]")]
        SystemBoolean,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Byte[]")]
        SystemByte,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.SByte[]")]
        SystemSByte,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Char[]")]
        SystemChar,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.UInt16[]")]
        SystemUInt16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.UInt32[]")]
        SystemUInt32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.UInt64[]")]
        SystemUInt64,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Int16[]")]
        SystemInt16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("System.Decimal[]")]
        SystemDecimal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class DataPropertyScalar : Property {
        
        private CS_Types typeField;
        
        private string sourceField;
        
        private int recordsetIndexField;
        
        public DataPropertyScalar() {
            this.recordsetIndexField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CS_Types type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int recordsetIndex {
            get {
                return this.recordsetIndexField;
            }
            set {
                this.recordsetIndexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class ScalarProperty : Property {
        
        private CS_Types typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CS_Types type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReportFileEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CalculationFileEntity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataFileEntity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public abstract partial class FileEntity : Entity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class ReportFileEntity : FileEntity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class CalculationFileEntity : FileEntity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class DataFileEntity : FileEntity {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class CodeEntityDataSource : DataSource {
        
        private object codeField;
        
        private CodeEntityDataSourceRead readField;
        
        private CodeEntityDataSourceCreate createField;
        
        private CodeEntityDataSourceUpdate updateField;
        
        private CodeEntityDataSourceDelete deleteField;
        
        private string typeNameField;
        
        /// <remarks/>
        public object Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public CodeEntityDataSourceRead Read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
            }
        }
        
        /// <remarks/>
        public CodeEntityDataSourceCreate Create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
            }
        }
        
        /// <remarks/>
        public CodeEntityDataSourceUpdate Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
        
        /// <remarks/>
        public CodeEntityDataSourceDelete Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class CodeEntityDataSourceRead {
        
        private string methodNameField;
        
        public CodeEntityDataSourceRead() {
            this.methodNameField = "Read";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Read")]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class CodeEntityDataSourceCreate {
        
        private string methodNameField;
        
        public CodeEntityDataSourceCreate() {
            this.methodNameField = "Create";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Create")]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class CodeEntityDataSourceUpdate {
        
        private string methodNameField;
        
        public CodeEntityDataSourceUpdate() {
            this.methodNameField = "Update";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Update")]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class CodeEntityDataSourceDelete {
        
        private string methodNameField;
        
        public CodeEntityDataSourceDelete() {
            this.methodNameField = "Delete";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Delete")]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class AssemblyEntityDataSource : DataSource {
        
        private AssemblyEntityDataSourceRead readField;
        
        private AssemblyEntityDataSourceCreate createField;
        
        private AssemblyEntityDataSourceUpdate updateField;
        
        private AssemblyEntityDataSourceDelete deleteField;
        
        private string assemblyPathField;
        
        private string typeNameField;
        
        /// <remarks/>
        public AssemblyEntityDataSourceRead Read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
            }
        }
        
        /// <remarks/>
        public AssemblyEntityDataSourceCreate Create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
            }
        }
        
        /// <remarks/>
        public AssemblyEntityDataSourceUpdate Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
        
        /// <remarks/>
        public AssemblyEntityDataSourceDelete Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string assemblyPath {
            get {
                return this.assemblyPathField;
            }
            set {
                this.assemblyPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class AssemblyEntityDataSourceRead {
        
        private string methodNameField;
        
        public AssemblyEntityDataSourceRead() {
            this.methodNameField = "Read";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Read")]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class AssemblyEntityDataSourceCreate {
        
        private string methodNameField;
        
        public AssemblyEntityDataSourceCreate() {
            this.methodNameField = "Create";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Create")]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class AssemblyEntityDataSourceUpdate {
        
        private string methodNameField;
        
        public AssemblyEntityDataSourceUpdate() {
            this.methodNameField = "Update";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Update")]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class AssemblyEntityDataSourceDelete {
        
        private string methodNameField;
        
        public AssemblyEntityDataSourceDelete() {
            this.methodNameField = "Delete";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Delete")]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class DBEntityDataSource : DataSource {
        
        private object listField;
        
        private object readField;
        
        private object createField;
        
        private object updateField;
        
        private object deleteField;
        
        private string providerField;
        
        private string connectionStringField;
        
        /// <remarks/>
        public object List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <remarks/>
        public object Read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
            }
        }
        
        /// <remarks/>
        public object Create {
            get {
                return this.createField;
            }
            set {
                this.createField = value;
            }
        }
        
        /// <remarks/>
        public object Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
        
        /// <remarks/>
        public object Delete {
            get {
                return this.deleteField;
            }
            set {
                this.deleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string connectionString {
            get {
                return this.connectionStringField;
            }
            set {
                this.connectionStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="modelex")]
    public partial class DBDataSource : DataSource {
        
        private string providerField;
        
        private string connectionStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string connectionString {
            get {
                return this.connectionStringField;
            }
            set {
                this.connectionStringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="modelex")]
    public partial class ModelExConfigurationLocal {
        
        private string tempLocationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tempLocation {
            get {
                return this.tempLocationField;
            }
            set {
                this.tempLocationField = value;
            }
        }
    }
}
